name: main

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build-specifics:
    strategy:
      matrix:
        job: [wafflingtaylors, moderndotnet]
    needs: generic
    name: "Render ${{ matrix.job }} FAQ document"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output
      - uses: docker://pandoc/latex:2.9
        with:
          args: about.md ./show-specifics/${{ matrix.job }}.md guest-faq.md --pdf-engine=xelatex -V geometry:"top=2cm, bottom=1.5cm, left=2cm, right=2cm" -o ${{ env.OUTPUT_FILENAME }} --toc
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.job }}-output
          path: ./${{ matrix.job }}-guest-faq.pdf

  generic:
    name: "Render Generic FAQ document"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir output  # create output dir
          # this will also include README.md
          # echo "::set-env name=FILELIST::$(printf '"%s" ' **.md)"
      - uses: docker://pandoc/latex:2.9
        with:
          args: guest-faq.md about.md --pdf-engine=xelatex -V geometry:"top=2cm, bottom=1.5cm, left=2cm, right=2cm" -o guest-faq.pdf --toc
      - uses: actions/upload-artifact@v2
        with:
          name: generic-output
          path: ./guest-faq.pdf